args = commandArgs(trailingOnly=TRUE)
library(vcfR)
vcf_input<-read.vcfR(args[1])
vcf_genlight<-vcfR2genlight(vcf_input)
gts <- t(as.matrix(vcf_genlight))
alt_counts<-rowSums(gts)
pdf(args[2])
hist(alt_counts, nclass=ncol(gts)*2, xlab="number of alt alleles", main="SFS")
dev.off()